version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6380:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password123
    volumes:
      - redis-data:/data
volumes:
  redis-data:
    driver: local